package llm

import "encoding/json"

// Protocol identifies the API protocol used to communicate with a model.
type Protocol string

const (
	ProtocolOpenAICompletions Protocol = "openai-completions"
)

// Role identifies the participant or source of a message.
type Role string

const (
	// RoleUser marks content that came from the user.
	RoleUser Role = "user"
	// RoleAssistant marks content generated by the assistant.
	RoleAssistant Role = "assistant"
	// RoleToolResult marks content returned by a tool call.
	RoleToolResult Role = "toolResult"
)

// ContentType identifies the shape of a message content block.
type ContentType string

const (
	// ContentText represents plain text content.
	ContentText ContentType = "text"
	// ContentThinking represents model reasoning content.
	ContentThinking ContentType = "thinking"
	// ContentToolCall represents a tool invocation requested by the assistant.
	ContentToolCall ContentType = "toolCall"
)

// ToolCall describes a request to invoke a named tool with JSON arguments.
type ToolCall struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// Content is a single block inside a message.
type Content struct {
	Type     ContentType `json:"type"`
	Text     string      `json:"text,omitempty"`
	Thinking string      `json:"thinking,omitempty"`
	ToolCall *ToolCall   `json:"toolCall,omitempty"`
}

// Message represents one item in the conversation context.
type Message struct {
	Role       Role      `json:"role"`
	Content    []Content `json:"content"`
	ToolCallID string    `json:"toolCallId,omitempty"`
	ToolName   string    `json:"toolName,omitempty"`
	IsError    bool      `json:"isError,omitempty"`
}

// ToolDefinition describes a tool that the model may call.
type ToolDefinition struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Parameters  json.RawMessage `json:"parameters"`
}

// Context contains the prompt, conversation history, and available tools.
type Context struct {
	SystemPrompt string           `json:"systemPrompt,omitempty"`
	Messages     []Message        `json:"messages"`
	Tools        []ToolDefinition `json:"tools,omitempty"`
}

// Model identifies the model and provider endpoint to use.
type Model struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Protocol Protocol `json:"protocol"`
	Provider string   `json:"provider"`
	BaseURL  string   `json:"baseUrl"`
}

// AssistantMessage is the final or partial response returned by a provider.
type AssistantMessage struct {
	Content    []Content `json:"content"`
	Model      string    `json:"model"`
	StopReason string    `json:"stopReason"`
}
